apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: gezx/vue-app:latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /girls
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /girls
              port: http
            periodSeconds: 5
