apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    newTag: 0.24.1
vars:
  - fieldref:
      fieldPath: metadata.name
    name: SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: ingress-nginx
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: nginx-template
  files:
    - configmap/nginx.tmpl
